name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Runing Test
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.cancel_token }}

      - uses: actions/checkout@v1
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: |
            yarn lint
            yarn tsc
            yarn test
