name: Testing

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2.0.0
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v1.1.1

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: yarn install
        run: |
          yarn install --frozen-lockfile

      - name: yarn test
        uses: GabrielBB/xvfb-action@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          run: |
            yarn package-ci
            yarn lint
            yarn tsc
            yarn test
            yarn build-e2e
            yarn test-e2e
