name: Build and Test

on: push

jobs:
  build-and-test:
    name: Runing Test
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ secrets.cancel_token }}

      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@HEAD
        with:
          working-directory: .cache/yarn

      - name: yarn install
        run: |
          yarn install --frozen-lockfile
        working-directory: .cache/yarn

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1.2
        with:
          run: |
            yarn package-ci
            yarn lint
            yarn tsc
            yarn test
            yarn build-e2e
            yarn test-e2e
        working-directory: .cache/yarn
